fragment AboutParts on About {
  __typename
  photo
  video
  general {
    __typename
    uk {
      __typename
      name
      profession
      education {
        __typename
        institution
      }
      experience {
        __typename
        point
      }
    }
    en {
      __typename
      name
      profession
      education {
        __typename
        institution
      }
      experience {
        __typename
        point
      }
    }
  }
  education {
    __typename
    uk {
      __typename
      title
      institutions {
        __typename
        period
        institution
      }
    }
    en {
      __typename
      title
      institutions {
        __typename
        period
        institution
      }
    }
  }
  career {
    __typename
    uk {
      __typename
      title
      institutions {
        __typename
        period
        institution
      }
    }
    en {
      __typename
      title
      institutions {
        __typename
        period
        institution
      }
    }
  }
  certificates {
    __typename
    photo
    description {
      __typename
      uk {
        __typename
        alt
      }
      en {
        __typename
        alt
      }
    }
  }
}

fragment BannerParts on Banner {
  __typename
  uk {
    __typename
    title
    description
  }
  en {
    __typename
    title
    description
  }
}

fragment ResultsParts on Results {
  __typename
  case {
    __typename
    date
    content {
      __typename
      uk {
        __typename
        title
        description
      }
      en {
        __typename
        title
        description
      }
    }
    before
    after
  }
}

fragment ReviewsParts on Reviews {
  __typename
  uk {
    __typename
    case {
      __typename
      date
      photo
      video
      name
      telegram
      review
    }
  }
  en {
    __typename
    case {
      __typename
      date
      photo
      video
      name
      telegram
      review
    }
  }
}
