export { default as HeroSection } from '@/sections/Hero/Hero';
export { default as AboutSection } from '@/sections/About/About';
export { default as AdvantagesSection } from '@/sections/Advantages/Advantages';
export { default as BannerSection } from '@/sections/Banner/Banner';
export { default as ResultsSection } from '@/sections/Results/Results';
export { default as FAQSection } from '@/sections/FAQ/FAQ';
export { default as ContactsSection } from '@/sections/Contacts/Contacts';
export { default as FeedbackSection } from '@/sections/Feedback/Feedback';
export { default as TreatmentDetailsSection } from '@/sections/TreatmentDetails/TreatmentDetails';
